done(ex1): первое решение
xp-rodion/go-yadro pull request #2
Opened 2024-03-27 17:29 UTC by xp-rodion

Решение первого задания
@kirreal
@maxan98
@vbelogrudov

2024-03-28 07:28 UTC, vbelogrudov requested changes
все очень неплохо, есть что поправить

2024-03-28 07:28 UTC, vbelogrudov commented on main/Makefile
> +run:
в run наверное нет необходимости, может я что-то не знаю? :)
Можно добавить цель clean по желанию. all обычно ставят первой целью, чтобы make без целей просто компилировал

2024-03-28 07:28 UTC, vbelogrudov commented on main/main.go
> +	sentence := flag.String("s", "", "Введите ваше предложение: ")
лучше воспользоваться flag.StringVar, чтобы не было указателей и разыменований. Также меньше будет аллокаций в куче. Под капотом flag.String все равно вызовет flag.StringVar - https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/flag/flag.go;l=890

2024-03-28 07:28 UTC, vbelogrudov commented on main/main.go
> +	return strings.Fields(*sentence)
лучше воспльзоваться более совершенной функцией strings.FieldsFunc(), чтобы разбивать входные данные не только по пробелам, но и, например, по знакам пунктуации

2024-03-28 07:28 UTC, vbelogrudov commented on main/main.go
> +func StemWords(words []string) {
в идеале бы возвратить слайс, а печатать уже в main. Нам эта функция еще не раз пригодится

2024-03-28 10:33 UTC, xp-rodion commented
@vbelogrudov залил фикс по замечаниям

2024-03-28 10:41 UTC, xp-rodion commented
Сделал небольшое ревью кода, хотел бы уточнить у вас для большой читаемости стоит ли возвращать значения явно, или если мое возвращаемое значение и название переменной указано при объявлении функции и возвращаю это неявно, обычным return, то это тоже валидное решение для читаемости?

2024-03-28 16:00 UTC, xp-rodion commented
@vbelogrudov исправил замечания, жду добра для закрытия данной задачи и PR

2024-03-30 13:51 UTC, vbelogrudov commented
привет! Все отлично работает . Единственное, что я пока не придумал, зачем нам может понадобиться TrimSpace, мы вроде все через регекс удалили лишнее.  Можно закрывать ПР и мержить.

2024-03-30 13:53 UTC, vbelogrudov commented
мы можем уточнить нормализатор и стеммер, когда будут реальные данные

2024-03-31 10:16 UTC, merged