done(ex4): первое решение
xp-rodion/go-yadro pull request #8
Opened 2024-04-21 21:09 UTC by xp-rodion

@vbelogrudov 
реализовал обычный и индексный поиск, вынес и разбил общую логику в internal, бенчмарки не написаны, отправлю чуть позже, ожидаю комментариев по коду и заданию в целом

2024-04-22 12:38 UTC, vbelogrudov requested changes
привет!

по коду замечаний особо нет, по тестам - есть паника :) А хочется -   https://imgs.xkcd.com/comics/mine_captcha.png 
Посмотри, пожалуйста:

➜  xp-rodion/go-yadro git:(tasks/ex4) ✗ ./xkcd -i -s "mines, captcha"                                
Using Index Search
Начало парсинга!
1 комиксов будут спаршены
Комиксы преобразованы, идет запись в бд, прерывание невозможно!
Загрузка в бд...
Конец парсинга!
Результат поиска
panic: runtime error: slice bounds out of range [:10] with capacity 8

2024-04-22 13:50 UTC, xp-rodion commented
@vbelogrudov 
извиняюсь, залил фикс с исправлением данной паники

2024-04-22 20:01 UTC, xp-rodion commented
@vbelogrudov 
дописал бенчмарки, есть **2** сценария запуска через make

**make benchmark_without_db** -  каждый функция в бенчмарке инциализирует БД и индекс сам!!

**make benchmark_with_db** - по началу запускается инциализационная функция, готовит БД и индекс, а далее функция бенчмарке занимается только поиском

2024-04-23 07:55 UTC, vbelogrudov requested changes
еще небольшая проблема
```

➜  xp-rodion/go-yadro git:(tasks/ex4) make      
make build
make[1]: Entering directory '/home/vbelogrudov/projects/course/xp-rodion/go-yadro'
go build -o xkcd ./cmd/xkcd
# xkcd/cmd/xkcd
cmd/xkcd/main.go:10:6: main redeclared in this block
	cmd/xkcd/initialize.go:8:6: other declaration of main
make[1]: *** [Makefile:7: build] Error 1
make[1]: Leaving directory '/home/vbelogrudov/projects/course/xp-rodion/go-yadro'
make: *** [Makefile:4: all] Error 2
```

2024-04-23 16:51 UTC, xp-rodion commented
@vbelogrudov 
пофиксил неудачное расположение функции инциализации, теперь должно быть в порядке

2024-04-24 09:02 UTC, vbelogrudov approved these changes
посмотри, пложалуйста, в будущем на
```

➜  xp-rodion/go-yadro git:(tasks/ex4) ✗ ./xkcd -c configs/config.yaml -i -s 'mines captcha'
Using Index Search
Начало парсинга!
1 комиксов будут спаршены
Комиксы преобразованы, идет запись в бд, прерывание невозможно!
Загрузка в бд...
Конец парсинга!

Результат поиска
Weight: 1; Url: https://imgs.xkcd.com/comics/git.png
Weight: 1; Url: https://imgs.xkcd.com/comics/planet_killer_comet_margarita.png
Weight: 1; Url: https://imgs.xkcd.com/comics/a_softer_robot.jpg
Weight: 1; Url: https://imgs.xkcd.com/comics/words_for_pets.png
```
хочется найти https://xkcd.com/2496  -> https://imgs.xkcd.com/comics/mine_captcha.png

2024-04-29 12:27 UTC, xp-rodion commented
@vbelogrudov учтено, добавил стемминг еще и titile в keywords

2024-04-29 12:27 UTC, merged